### ISSUE TITLE
[Question] AccountTextField 수정

### ISSUE THREAD

**Issue by kyustudyo** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#20]
## Issues and steps to reproduce
@LentoAssai 님이 작성한 아래의 코드를 잘 이용하고 있습니다.
```Swift
struct AccountTextField: View {
    @State private var account = ""
    @State private var showSheet = false
    @State private var bank = "은행 선택"
```
제가 이를  
```Swift
struct DecorateCardView: View 
```
에서 
아래와 같이 불러왔습니다.
```Swift
AccountTextField()
```
그러나 private로 선언된 account와 back 프로퍼티를 DecorateCardView에서 불러올 수 없습니다. 
저는 account와 bank 프로퍼티를 DecorateCardView에서 읽어서 PreviewCardView의 매개변수로 넣고 싶습니다.
현재는 카드를 decorate 하는 뷰에서 은행의 계좌를 입력하여도 카드에 계좌번호가 반영되지 않거든요..
이를 위해 AccountTextField를 제가 수정하여도 될지 여쭙고싶습니다.

**Comment by LentoAssai** [comment]
코드 수정하셔도 괜찮을 것 같습니다.
제가 private을 쓴 것은 @State 사용 시 private 사용을 권장하기 때문에 사용했습니다.

**Comment by kyustudyo** [comment]
중요한 것 같습니다.
State 사용시 Private 키워드 사용을 권장하는군요!
참고하겠습니다.
