### ISSUE TITLE
[Package] HalfASheet패키지 사용관련

### ISSUE THREAD

**Issue by kimscastle** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#26]
https://github.com/franklynw/HalfASheet

MainView에서 DonCard를 누르면 하프시트를 띄워야하는데 여러가지 방법중에 가장 괜찮은 패키지인거같아서 사용하려합니다
.sheet와 작동방식은 유사하고 높이를 조절할수있다는장점이있습니다.

SheetView에 closebutton이 default로 있고 가장큰 장점은 각각의 SheetView에 padding을 주지 않더라도 자동으로 적당한 위치에 내용들이 위치가 되어있습니다. 각각의 SheetView를 따로 preview로 보면 패딩이없지만 Main에서 SheetView로 보면 정렬이 되어있습니다
<p align="left">
<img width="260" alt="스크린샷 2022-06-09 오전 1 00 14" src="https://user-images.githubusercontent.com/99013115/172663548-d52c9d2e-0384-4d8d-b9f6-d58e5483261c.png">
<img width="250" alt="스크린샷 2022-06-09 오전 1 00 54" src="https://user-images.githubusercontent.com/99013115/172663676-0bbcf55c-7dd7-471a-9cbf-f6d31b8f475b.png">
</p>

스크린샷에 closebutton이 없는이유는 색깔을 흰색으로 만들어서 그렇습니다

문제가 있다면 HalfSheet를 패키지를이용해구현하게되면 시트를 드래그했을 때 커지지 않는다는점인데 이부분은 디자이너분과 상의를 해봐야할거같습니다. Sheet내부를 ScrollView로 구현을 하기때문에 이대로도 괜찮을거같긴하지만 만약에 fullSheet로도 보여져야한다면 추후에 다른 방법을 가져와서 사용해보고 우선은 이 패키지로 하프시트를 구현해보겠습니다

**Comment by chaneeii** [comment]
HalfASheet 라이브러리 잘 봤습니다!

확인해보면서 다른 라이브러리들을 찾았는데 좋은 것 같아 공유드려요! 
아무래도 저희 내용이 fullSheet 로 보여져야하는 기능적인 부분들이 많아 개인적으로는 아래 라이브러리들이 좋을 것 같아 보입니다.
(이유 : 리스트로 데이터를 보여주고 있어서 하프모달에서는 UX 가 떨어지는 느낌이 크네요)
- https://github.com/mtj0928/ResizableSheet
- https://github.com/exyte/PopupView
