### ISSUE TITLE
"Multiple commands produce ~ " 에러 해결

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#3]
문제상황
===

"File.swift" 임시 파일을 여러 디렉토리에서 가지고 있는 상태로 빌드가 안됩니다.

<img width="805" alt="Screen Shot 2022-06-01 at 22 35 03" src="https://user-images.githubusercontent.com/88371913/171417248-25f94d30-d481-4ffe-b12e-6eed7673ad36.png">

해결방안을 아시는 분은 코멘트 부탁드립니다!

@luminouxx @Asher3576 @chaneeii @kyustudyo @kimscastle

**Comment by LentoAssai** [comment]
[#3]
해결
===
"File.swift" 같은 이름을 가진 파일들 때문에 문제가 생기는 것 같습니다.
파일 이름들을 각기 다른 이름으로 설정하고 빌드하면 문제가 해결됩니다.

**Comment by luminouxx** [comment]
Good
잘 해결하셨군요
