### ISSUE TITLE
[Check] Navigation 관련 이슈

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#37]
페이지 연결이 매끄럽지가 않아 수정 작업을 하며 어떤 것들을 수정했는지와 작업하며 느낀 점들 가운데 공유할만한 내용들이 있어서 이슈를 남깁니다.

# 회원가입 또는 로그인 플로우, 메인 페이지 플로우 구분
앱을 실행 시 로그인이 되어있지 않다면 회원가입 또는 로그인 플로우를 보여줘야하고, 그렇지 않다면 바로 메인 페이지 플로우를 보여줘야 합니다.
```swift
class UserStateViewModel: ObservableObject {
    
    @Published var isLoggedIn = false
    
    func signIn() {
        isLoggedIn = true
    }
    
    func signOut() {
        isLoggedIn = false
    }
}
```
우선 Model 디렉토리에 UserStateViewModel이란 클래스를 생성합니다. 이를 통해 로그인이 되어있는지, 그렇지 않은지를 구분할겁니다.

```swift
@main
struct DonWorryApp: App {
    @StateObject var userStateViewModel = UserStateViewModel()
    
    var body: some Scene {
        WindowGroup {
            NavigationView {
                ApplicationSwitcher()
            }
            .environmentObject(userStateViewModel)
        }
    }
}

struct ApplicationSwitcher: View {
    @EnvironmentObject var vm: UserStateViewModel
    
    var body: some View {
        if vm.isLoggedIn {
            HomeView(currentUser: user1)
        } else {
            SignInView()
        }
    }
}
```
이후 앱 파일 DonWorryApp.swift 파일에 위와 같이 코드를 작성하였습니다. (현재 메인에 있는 코드와 조금 다른 것은 제가 수정한 것도 있지만 이해를 위해 지금 설명하는 코드만 작성하였고 기존에 있던 AppDelegate 관련 코드는 잠시 삭제하였습니다.)
ApplicationSwitcher에서 만약 로그인이 되어있다면 HomeView를 보여줄 것이고, 로그인을 해야한다면 SignInView를 보여줄 것입니다.
그림으로 나타내면 다음과 같습니다.
<p>
<img width="400" alt="Screen Shot 2022-06-11 at 0 02 51" src="https://user-images.githubusercontent.com/88371913/173094386-1d91fd34-12d2-4c08-91a8-03adc90396c6.png">
</p>

# NavigationBar가 자꾸 쌓이는 이슈 해결 및 페이지 연결
### 원인
NavigationView가 여러개 쌓여서 생기는 문제입니다. NavigationView 하위 계층에 있는 View 들에서 다시 NavigationView를 사용하면 안됩니다.
현재 이 이슈가 생긴 원인은 NavigationView를 가지고 있는 View(루트 뷰라고 잠시 하겠습니다.) 에서 하위 뷰로 NavigationLink를 통해 이동한 상태에서 다시 NavigationView로 돌아오는 로직을 if문으로 작성하여 하위 뷰에서 루트 뷰가 쌓이기 때문입니다. 따라서 하위 뷰에서 루트 뷰로 dismiss하는 코드를 다시 작성하였습니다.

### 해결방법
여러 페이지를 한번에 dismiss 시키는 것을 공부하며 알게된 방법은 2가지가 있는데 이번에 사용하게 된 방법은 저희 앱에 맞게 조금은 변형된 형태입니다. 대표적으로 NavigationLink를 사용할 때 isActive를 같이 사용하는 방법으로 구현을 하지만, 저희는 공용 컴포넌트로 버튼을 사용하고, 이 버튼을 눌렀을 때 NavigationLink를 사용해야 하기 때문에 (NavigationLink의 Label을 버튼으로 구현하면 제대로 작동하지 않는 이슈가 있습니다.) tag, selection 등을 사용하는 NavigationLink를 사용하며 dismiss시키는 방법을 생각해보게 되었습니다.
버튼이 눌렸을 때 selection을 미리 설정해둔 tag와 같게 만들면 NavigationLink를 타고 페이지 이동을 하기 때문에 selection이 isActive의 역할을 충분히 할 수 있다고 판단했고, 따라서 isActive로 dismiss시키는 방법에서 조금 변형하여 selection을 하위 페이지로 Binding으로 넘겨주면서 최종 하위 페이지에서 루트 뷰로 다시 넘어오고 싶을 때 selection의 값을 초기화시켜 모든 페이지들을 한번에 dismiss하는 방식으로 구현하였습니다.
따라서 모든 NavigationLink를 tag와 selection을 사용하는 것으로 코드를 변경하였습니다.

**Comment by LentoAssai** [comment]
NavigationView를 전체로 감싸는거는 생각하지 못했었네요. 바로 수정해도 될 것 같아요!

**Comment by luminouxx** [comment]
User defaults를 안쓰고 저장하는 방법이 있었군요 !
고정관념에서 빠져보도록 하겠습니다 버리님!
