### ISSUE TITLE
메인카드에 정산여부카드 컬러관련 이슈입니다

### ISSUE THREAD

**Issue by kimscastle** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#5]
아래이미지가 컬러익스텐션에있는 메인블루컬러를 넣은건데
<img width="1157" alt="스크린샷 2022-06-02 오후 1 54 59" src="https://user-images.githubusercontent.com/99013115/171555595-ffc54ebc-45f0-487c-8601-90c04c5aba9b.png">

스케치에서 파란색이랑 xcode에서 파란색이 좀 달라서
<img width="292" alt="스크린샷 2022-06-02 오후 1 55 18" src="https://user-images.githubusercontent.com/99013115/171555639-90b9d0bb-ff45-4f17-b89a-031706c3edf6.png">

 그룹을 해제 해보니 아래처럼 이렇게 되어있네요...? 색깔을 다시 맞춰할까요?
<img width="354" alt="스크린샷 2022-06-02 오후 1 55 44" src="https://user-images.githubusercontent.com/99013115/171555688-b1fb5d7b-e6a0-45f2-9a82-63174efc1899.png">

@Asher3576 
@chaneeii

**Comment by Asher3576** [comment]
@kimscastle 

업무에 수고가 많으십니다.
일단 메인 블루 컬러와 다른 색상입니다! 너무 다 같은 채도가 높은 색상이 많으니 부담스러운 면이 있어서 
카드를 채도를 조금 낮췄습니다!

그리고 아래 사진에서도 조금 변화가 있습니다! ui 작업하실때 Page를 "Prototype" 에서 참고 바랍니다.
감사합니다.
